---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-python-dependencies:
        # pip: Only group minor and patch updates
        update-types: [minor, patch]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-actions-dependencies:
        # GitHub Actions: Only group minor and patch updates
        update-types: [minor, patch]
